/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.matrizinversalambda;

import javax.swing.JOptionPane;

/**
 *
 * @author MIGUEL VILLACRES
 */
public class FrameMatrizInversaVillacres extends javax.swing.JFrame {

    /**
     * Creates new form FrameMatrizInversaVillacres
     */
    public FrameMatrizInversaVillacres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtElemento00 = new javax.swing.JTextField();
        txtElemento02 = new javax.swing.JTextField();
        txtElemento01 = new javax.swing.JTextField();
        txtElemento10 = new javax.swing.JTextField();
        txtElemento11 = new javax.swing.JTextField();
        txtElemento12 = new javax.swing.JTextField();
        txtElemento20 = new javax.swing.JTextField();
        txtElemento21 = new javax.swing.JTextField();
        txtElemento22 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnMatrizInversa = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtElement00 = new javax.swing.JTextField();
        txtElement02 = new javax.swing.JTextField();
        txtElement10 = new javax.swing.JTextField();
        txtElement11 = new javax.swing.JTextField();
        txtElement21 = new javax.swing.JTextField();
        txtElement22 = new javax.swing.JTextField();
        txtElement01 = new javax.swing.JTextField();
        txtElement20 = new javax.swing.JTextField();
        txtElement12 = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtElemento00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento00ActionPerformed(evt);
            }
        });

        txtElemento02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento02ActionPerformed(evt);
            }
        });

        txtElemento01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento01ActionPerformed(evt);
            }
        });

        txtElemento10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento10ActionPerformed(evt);
            }
        });

        txtElemento11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento11ActionPerformed(evt);
            }
        });

        txtElemento12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento12ActionPerformed(evt);
            }
        });

        txtElemento20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento20ActionPerformed(evt);
            }
        });

        txtElemento21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento21ActionPerformed(evt);
            }
        });

        txtElemento22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElemento22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtElemento20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElemento21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElemento22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtElemento10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElemento11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElemento12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtElemento00, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElemento01, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElemento02, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElemento00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElemento01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElemento02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElemento10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElemento11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElemento12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElemento20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElemento21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElemento22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INVERSA DE UNA MATRIZ 3X3");

        btnMatrizInversa.setText("MATRIZ INVERSA");
        btnMatrizInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizInversaActionPerformed(evt);
            }
        });

        txtElement00.setEditable(false);
        txtElement00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement00ActionPerformed(evt);
            }
        });

        txtElement02.setEditable(false);
        txtElement02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement02ActionPerformed(evt);
            }
        });

        txtElement10.setEditable(false);
        txtElement10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement10ActionPerformed(evt);
            }
        });

        txtElement11.setEditable(false);
        txtElement11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement11ActionPerformed(evt);
            }
        });

        txtElement21.setEditable(false);
        txtElement21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement21ActionPerformed(evt);
            }
        });

        txtElement22.setEditable(false);
        txtElement22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement22ActionPerformed(evt);
            }
        });

        txtElement01.setEditable(false);
        txtElement01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement01ActionPerformed(evt);
            }
        });

        txtElement20.setEditable(false);
        txtElement20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement20ActionPerformed(evt);
            }
        });

        txtElement12.setEditable(false);
        txtElement12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElement12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtElement02, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElement12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtElement22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtElement01, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElement11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElement21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtElement00, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtElement10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtElement20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElement00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElement10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElement20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElement11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElement01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElement21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElement22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElement02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtElement12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatrizInversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(101, 101, 101)
                        .addComponent(btnMatrizInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtElemento00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento00ActionPerformed

    private void txtElemento02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento02ActionPerformed

    private void txtElemento01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento01ActionPerformed

    private void txtElemento10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento10ActionPerformed

    private void txtElemento11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento11ActionPerformed

    private void txtElemento12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento12ActionPerformed

    private void txtElemento20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento20ActionPerformed

    private void txtElemento21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento21ActionPerformed

    private void txtElemento22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElemento22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElemento22ActionPerformed

    private void btnMatrizInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizInversaActionPerformed
        try {
            double[][] matriz = new double[3][3];

            // Obtenemos los valores de la interfaz gráfica para la matriz de la izquierda
            matriz[0][0] = Double.parseDouble(txtElemento00.getText());
            matriz[0][1] = Double.parseDouble(txtElemento01.getText());
            matriz[0][2] = Double.parseDouble(txtElemento02.getText());

            matriz[1][0] = Double.parseDouble(txtElemento10.getText());
            matriz[1][1] = Double.parseDouble(txtElemento11.getText());
            matriz[1][2] = Double.parseDouble(txtElemento12.getText());

            matriz[2][0] = Double.parseDouble(txtElemento20.getText());
            matriz[2][1] = Double.parseDouble(txtElemento21.getText());
            matriz[2][2] = Double.parseDouble(txtElemento22.getText());

            // Calculamos la inversa
            double[][] inversa = calcularMatrizInversa(matriz);

            // Mostramos la matriz inversa en los campos correspondientes
            txtElement00.setText(String.valueOf(inversa[0][0]));
            txtElement01.setText(String.valueOf(inversa[0][1]));
            txtElement02.setText(String.valueOf(inversa[0][2]));

            txtElement10.setText(String.valueOf(inversa[1][0]));
            txtElement11.setText(String.valueOf(inversa[1][1]));
            txtElement12.setText(String.valueOf(inversa[1][2]));

            txtElement20.setText(String.valueOf(inversa[2][0]));
            txtElement21.setText(String.valueOf(inversa[2][1]));
            txtElement22.setText(String.valueOf(inversa[2][2]));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMatrizInversaActionPerformed

    private void txtElement00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement00ActionPerformed

    private void txtElement02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement02ActionPerformed

    private void txtElement10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement10ActionPerformed

    private void txtElement11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement11ActionPerformed

    private void txtElement21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement21ActionPerformed

    private void txtElement22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement22ActionPerformed

    private void txtElement01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement01ActionPerformed

    private void txtElement20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement20ActionPerformed

    private void txtElement12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElement12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtElement12ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private double[][] calcularMatrizInversa(double[][] matriz) {
    double det = calcularDeterminante(matriz);
    if (det == 0) {
        throw new ArithmeticException("La matriz no tiene inversa (determinante es 0)");
    }
    double[][] adjunta = calcularAdjunta(matriz);
    double[][] inversa = new double[3][3];
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            inversa[i][j] = adjunta[i][j] / det;
        }
    }
    return inversa;
}

private double calcularDeterminante(double[][] matriz) {
    return matriz[0][0] * (matriz[1][1] * matriz[2][2] - matriz[1][2] * matriz[2][1])
           - matriz[0][1] * (matriz[1][0] * matriz[2][2] - matriz[1][2] * matriz[2][0])
           + matriz[0][2] * (matriz[1][0] * matriz[2][1] - matriz[1][1] * matriz[2][0]);
}

private double[][] calcularAdjunta(double[][] matriz) {
    double[][] adjunta = new double[3][3];
    adjunta[0][0] = matriz[1][1] * matriz[2][2] - matriz[1][2] * matriz[2][1];
    adjunta[0][1] = -(matriz[1][0] * matriz[2][2] - matriz[1][2] * matriz[2][0]);
    adjunta[0][2] = matriz[1][0] * matriz[2][1] - matriz[1][1] * matriz[2][0];
    adjunta[1][0] = -(matriz[0][1] * matriz[2][2] - matriz[0][2] * matriz[2][1]);
    adjunta[1][1] = matriz[0][0] * matriz[2][2] - matriz[0][2] * matriz[2][0];
    adjunta[1][2] = -(matriz[0][0] * matriz[2][1] - matriz[0][1] * matriz[2][0]);
    adjunta[2][0] = matriz[0][1] * matriz[1][2] - matriz[0][2] * matriz[1][1];
    adjunta[2][1] = -(matriz[0][0] * matriz[1][2] - matriz[0][2] * matriz[1][0]);
    adjunta[2][2] = matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0];
    return adjunta;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMatrizInversaVillacres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMatrizInversaVillacres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMatrizInversaVillacres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMatrizInversaVillacres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMatrizInversaVillacres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatrizInversa;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtElement00;
    private javax.swing.JTextField txtElement01;
    private javax.swing.JTextField txtElement02;
    private javax.swing.JTextField txtElement10;
    private javax.swing.JTextField txtElement11;
    private javax.swing.JTextField txtElement12;
    private javax.swing.JTextField txtElement20;
    private javax.swing.JTextField txtElement21;
    private javax.swing.JTextField txtElement22;
    private javax.swing.JTextField txtElemento00;
    private javax.swing.JTextField txtElemento01;
    private javax.swing.JTextField txtElemento02;
    private javax.swing.JTextField txtElemento10;
    private javax.swing.JTextField txtElemento11;
    private javax.swing.JTextField txtElemento12;
    private javax.swing.JTextField txtElemento20;
    private javax.swing.JTextField txtElemento21;
    private javax.swing.JTextField txtElemento22;
    // End of variables declaration//GEN-END:variables
}
